sudo: required
dist: trusty

services:
  - docker

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

branches:
  only:
    - master

env:
  global:
    - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
    # CHEF_VERSION is only for unit tests, not for test-kitchen:
    - TESTS="style unit"
    # Split up the test-kitchen run to avoid exceeding 50 minutes:
    - CHEF_VERSION=12 TESTS="integration" KITCHEN_INSTANCE=default-centos-6
    - CHEF_VERSION=12 TESTS="integration" KITCHEN_INSTANCE=default-centos-7
    - CHEF_VERSION=12 TESTS="integration" KITCHEN_INSTANCE=default-ubuntu-1404
    - CHEF_VERSION=12 TESTS="integration" KITCHEN_INSTANCE=default-ubuntu-1604
    - CHEF_VERSION=13 TESTS="integration" KITCHEN_INSTANCE=default-centos-6
    - CHEF_VERSION=13 TESTS="integration" KITCHEN_INSTANCE=default-centos-7
    - CHEF_VERSION=13 TESTS="integration" KITCHEN_INSTANCE=default-ubuntu-1404
    - CHEF_VERSION=13 TESTS="integration" KITCHEN_INSTANCE=default-ubuntu-1604

install: echo "skip bundle install"

# Ensure we make ChefDK's Ruby the default
before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef --version
  - cookstyle --version
  - foodcritic --version

script:
  - chef exec rake $TESTS
